[project]
name = 'crisis-chime'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.dao]
path = 'contracts/dao.clar'
clarity_version = 2
epoch = 2.5

[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 2
epoch = 2.5

[contracts.token]
path = 'contracts/token.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting]
path = 'contracts/voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
